* Ports
A collection of portfiles specific to Atlas for building webkit2-gtk.

* Usage
1. Clone this repository to a path of your choosing. The path is
   irrelevant.
2. Edit your =/opt/local/etc/macports/sources.conf= file to include a
   link to the location of this repository on your disk.
   + As an example, if you had cloned this repository to
     =/var/local/ports= you would add a line above the default source
     in =sources.conf= with the following syntax:
     =file:///var/local/ports=
3. After setting up your new source, you will need to execute:
   =sudo port selfupdate= for MacPorts to update the portindex

Your set-up is now complete and you can install ports from this ports
tree! When a port is not found in this ports tree, it will fallback to
the default MacPorts official source.

** Transferring archives

easye has slow hardware; webkit2-gtk-devel is a big build.

#+begin_example
<easye> I produced a binary from a modified port.  How do I install it on                            
        another host?  Placing the pkg in                                                            
        /opt/local/var/macports/software/MUMBLE/*.tbz on the new machine                             
        didn't seem to do the trick as `port -b install MUMBLE` is building                          
        the port instead.                                               [23:26]                      
*** Hasimir (~hfenring@unaffiliated/hasimir) has quit: Ping timeout: 246                             
    seconds                                                             [23:27]                      
* easye needs a faster laptop.                                          [23:29]                      
*** Hasimir (~hfenring@unaffiliated/hasimir) has joined channel #macports                            
                                                                        [23:32]                      
<jmr> easye: the full story is                                                                       
      https://trac.macports.org/wiki/howto/ShareArchives2               [23:33]                      
<jmr> but if you only want to transfer one archive there is a shortcut                               
<jmr> the magic place is ${prefix}/var/macports/incoming/verified       [23:34]                      
<easye> jmz:  thanks!                                                   [23:43]    
#+end_example

